(function(s,c){typeof exports=="object"&&typeof module<"u"?c(require("react"),require("react-dom")):typeof define=="function"&&define.amd?define(["react","react-dom"],c):(s=typeof globalThis<"u"?globalThis:s||self,c(s.React,s.ReactDOM))})(this,function(s,c){"use strict";var p={exports:{}},d={};/**
 * @license React
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var j=s,y=Symbol.for("react.element"),v=Symbol.for("react.fragment"),_=Object.prototype.hasOwnProperty,R=j.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,g={key:!0,ref:!0,__self:!0,__source:!0};function h(n,e,m){var r,i={},l=null,o=null;m!==void 0&&(l=""+m),e.key!==void 0&&(l=""+e.key),e.ref!==void 0&&(o=e.ref);for(r in e)_.call(e,r)&&!g.hasOwnProperty(r)&&(i[r]=e[r]);if(n&&n.defaultProps)for(r in e=n.defaultProps,e)i[r]===void 0&&(i[r]=e[r]);return{$$typeof:y,type:n,key:l,ref:o,props:i,_owner:R.current}}d.Fragment=v,d.jsx=h,d.jsxs=h,p.exports=d;var t=p.exports,f={},u=c;f.createRoot=u.createRoot,f.hydrateRoot=u.hydrateRoot;const E=()=>{const[n,e]=s.useState([]),[m,r]=s.useState(!0),[i,l]=s.useState(null);return s.useEffect(()=>{(async()=>{try{const a=await fetch("/api/testimonials/top");if(!a.ok)throw new Error("Failed to fetch testimonials");const x=await a.json();console.log("Testimonials data:",x),e(x)}catch(a){console.error("Fetch error:",a),l(a instanceof Error?a.message:"An error occurred")}finally{r(!1)}})()},[]),m?t.jsx("div",{className:"testimonials-loading",children:"Loading..."}):i?t.jsxs("div",{className:"testimonials-error",children:["Error: ",i]}):t.jsx("div",{className:"testimonials-grid",children:n.map(o=>t.jsxs("div",{className:"testimonial-bubble-container",children:[t.jsxs("div",{className:"bubble",children:[t.jsx("h3",{children:o.title}),t.jsx("p",{children:o.body})]}),t.jsx("div",{className:"testimonial-avatar",children:t.jsx("img",{src:"/assets/img/avatar.png",alt:o.personName,width:"56",height:"56"})}),t.jsxs("div",{className:"testimonial-info",children:[t.jsx("strong",{children:o.personName}),t.jsx("span",{children:o.personCompany})]})]},o.id))})},w=n=>{const e=document.getElementById(n);e?f.createRoot(e).render(t.jsx(s.StrictMode,{children:t.jsx(E,{})})):console.error(`Element with id '${n}' not found`)};window.TestimonialsWidget={init:w}});
